### ISSUE TITLE
Data repositories (metastudent-data / metastudent-data-2)

### ISSUE THREAD

**Issue by anapetrovska** [Rostlab/MetaStudent.backup#1]
@jmcejuela

In "HOWTO access rostlab svn repos" there is a note next to our repository: Note: we're still trying to find the data repositories (should be metastudent-data and metastudent-data-2). Can you please tell me what we should migrate to git (metastudent, metastudent-data or metastudent-data-2)?

Thanks!

**Comment by jmcejuela** [comment]
metastudent foremost

But you will need metastudent-data(s) -- I guess they can be served as perhaps github files
